description = "The NixTips.io theme."
features = []
homepage = "https://github.com/darioghilardi/nixtips"
license = "MIT"
min_version = "0.88.0"
name = "nixtips"
tags = ["Hugo", "Tailwind CSS", "theme", "starter", "boilerplate"]

[author]
homepage = "https://github.com/darioghilardi/"
name = "Dario Ghilardi"
homepage = "https://github.com/razielgn/"
name = "Federico Ravasio"
