baseURL = 'https://nixtips.io/'
languageCode = 'en-us'
theme = 'nixtips'
title = 'NixTips'
paginate = 6
paginatePath = '/'
summaryLength = 50
enableRobotsTXT = true

[params]
  og_image = "/images/nixtips_card.png"
  description = "Stories and tips from using Nix in production."

[security.exec]
osEnv = ['.*']

disableKinds = ["page", "section", "taxonomy", "term"]

[module]
[module.hugoVersion]
extended = false
min = "0.112.0"
