description = "The ArchiWind.io theme."
features = []
homepage = "https://github.com/nablaflow/archiwind.io"
license = "MIT"
min_version = "0.88.0"
name = "archiwind"
tags = ["Hugo", "Tailwind CSS", "theme", "starter", "boilerplate"]

[author]
homepage = "https://github.com/darioghilardi/"
name = "Dario Ghilardi"
