name: ci-production

on:
  push:
    branches:
      - master

env:
  PROJECT_NAME: nixtips

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      # - uses: cachix/cachix-action@v14
      #   with:
      #     name: nablaflow
      #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      #   env:
      #     USER: runner

      - name: checks
        run: nix flake check -L

      - name: build
        run: nix build . -L

      - name: copy artifacts
        run: |
          mkdir build
          cp -RL ./result/build/* ./build

      - name: deploy
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ env.PROJECT_NAME}}
          directory: ./build
          branch: master
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'
